var cyrilicAlphabet = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя";
var cyrilicAlphabetUpper = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ";

var russContent = [

{ 'name': "Unit 1 Vocabulary",
  'vocab': [
    ["hello (on the phone)", "алло"],
    ["banana", "банан"],
    ["bank", "банк"],
    ["water", "вода"],
    ["here", "вот"],
    ["you (plur./form.)", "вы"],
    ["yes", "да"],
    ["house", "дом"],
    ["at home", "дома"],
    ["smoke", "дым"],
    ["lamp", "лампа"],
    ["the Moon", "Луна"],
    ["mother", "мама"],
    ["we", "мы"],
    ["he", "он"],
    ["she", "она"],
    ["father", "папа"],
    ["plan", "план"],
    ["there", "там"],
    ["telephone", "телефон"],
    ["here", "тут"],
    ["you (sing./inf.)", "ты"],
    ["photograph", "фото"],
    ["that/this is", "это"],
  ],
},

{ 'name': "Unit 2 Vocabulary",
  'vocab': [
    ["bus", "автобус"],
    ["letter of the alphabet", "буква"],
    ["brother", "брат"],
    ["city", "город"],
    ["group", "группа"],
    ["male friend", "друг"],
    ["factory", "завод"],
    ["tomorrow", "завтра"],
    ["sound", "звук"],
    ["how", "как"],
    ["map", "карта"],
    ["club", "клуб"],
    ["when", "когда"],
    ["room", "комната"],
    ["male cat", "кот"],
    ["who", "кто"],
    ["onion", "лук"],
    ["few", "мало"],
    ["many", "много"],
    ["milk", "молоко"],
    ["window", "окно"],
    ["park", "парк"],
    ["bad", "плохо"],
    ["weather", "погода"],
    ["female friend", "подруга"],
    ["story", "рассказ"],
    ["fish", "рыба"],
    ["word", "слово"],
    ["dog", "собака"],
    ["juice", "сок"],
    ["table", "стол"],
    ["country", "страна"],
    ["chair", "стул"],
    ["bag", "сумка"],
    ["soup", "суп"],
    ["son", "сын"],
    ["cheese", "сыр"],
    ["cake", "торт"],
    ["lesson", "урок"],
    ["in the morning", "утром"],
    ["cold", "холодно"],

    ['What is your name?', 'Как вас зовут?'],
    ['wait a minute', 'минуту'],
    ['thank you', 'спасибо'],
  ],
},

{ 'name': "Unit 3 Vocabulary",
  'vocab': [
    ['grandmother', 'бабушка'],
    ['your (form./plur., masc.)', 'ваш'],
    ['give (inf.)', 'дай'],
    ['his', 'его'],
    ['her', 'её'],
    ['hedgehog', 'ёж'],
    ['fur tree', 'ёлка'],
    ['it is hot', 'жарко'],
    ['wife', 'жена'],
    ['yellow', 'жёлтый'],
    ['giraffe', 'жираф'],
    ['bug', 'жук'],
    ['magazine', 'журнал'],
    ['breakfast', 'завтрак'],
    ['umbrella', 'зонт'],
    ['their', 'их'],
    ['pencil', 'карандаш'],
    ['class', 'класс'],
    ['spoon', 'ложка'],
    ['May (month)', 'май'],
    ['car', 'машина'],
    ['may/may I', 'можно'],
    ['mine/my (masc.)', 'мой'],
    ['mine/my (fem.)', 'моя'],
    ['our (masc.)', 'наш'],
    ['knife', 'нож'],
    ['garden', 'сад'],
    ['your (inf./sing., masc.)', 'твой'],

    ['your (inf./sing., fem.)', 'твоя'],
    ['also', 'тоже'],
    ['good', 'хорошо'],
    ['hat', 'шапка'],
    ['scarf', 'шарф'],
    ['closet', 'шкаф'],
    ['school', 'школа'],
    ['state', 'штат'],
    ['examination', 'экзамен'],
    ['building floor', 'этаж'],
    ['humor', 'юмор'],
    ['attorney/lawyer', 'юрист'],
    ['I', 'я'],
    ['apple', 'яблоко'],
    ['berry', 'ягода'],
    ['language', 'язык'],

    ['Goodbye', 'До свидания'],
    ['Hello/How do you do? (inf.)', 'Здравствуй'],
    ['How are you doing?', 'Как дела?'],
    ['Really?', 'Правда?'],
  ],
},

{ 'name': "Unit 4 Vocabulary",
  'vocab': [
    ['address', 'адрес'],
    ['album', 'альбом'],
    ['pharmacy', 'аптека'],
    ['lecture hall', 'аудитория'],
    ['vase', 'ваза'],
    ['in the evening', 'вечером'],
    ['thing', 'вещь'],
    ['doctor', 'врач'],
    ['always', 'всегда'],
    ['newspaper', 'газета'],
    ['garage', 'гараж'],
    ['where', 'где'],
    ['grandfather', 'дедушка'],
    ['director', 'директор'],
    ['during the day', 'днём'],
    ['uncle', 'дядя'],
    ['here', 'здесь'],
    ['in winter', 'зимой'],
    ['name', 'имя'],
    ['engineer', 'инженер'],
    ['institute', 'институт'],
    ['book', 'книга'],
    ['of course/naturally', 'конечно'],
    ['in the summer', 'летом'],
    ['leaf', 'лист'],
    ['place/seat', 'место'],
    ['shop/store', 'магазин'],
    ['mother', 'мать'],
    ['subway', 'метро'],

    ['sea', 'море'],
    ['museum', 'музей'],
    ['not', 'не'],
    ['no', 'нет'],
    ['dormitory', 'общежитие'],
    ['in the fall', 'осенью'],
    ['stop/station', 'остановка'],
    ['very', 'очень'],
    ['song', 'песня'],
    ['a letter (in the mail)', 'письмо'],
    ['town square', 'площадь'],
    ['call me (inf.)', 'позвони'],
    ['call me (form.)', 'позвоните'],
    ['show me (inf.)', 'покажи'],
    ['show me (form.)', 'покажите'],
    ['outpatient clinic', 'поликлиника'],
    ['post office', 'почта'],
    ['instructor', 'преподаватель'],
    ['pen', 'ручка'],
    ['rice', 'рис'],
    ['roses', 'розы'],
    ['today', 'сегодня'],
    ['now', 'сейчас'],
    ['family', 'семья'],
    ['sister', 'сестра'],
    ['on the left', 'слева'],
    ['dictionary', 'словарь'],
    ['on the right', 'справа'],
    ['cafeteria', 'столовая'],

    ['male student', 'студент'],
    ['female student', 'студентка'],
    ['theater', 'театр'],
    ['it is warm', 'тепло'],
    ['notebook', 'тетрадь'],
    ['aunt', 'тётя'],
    ['only', 'только'],
    ['university', 'университет'],
    ['exercise', 'упражнение'],
    ['textbook', 'учебник'],
    ['cup', 'чашка'],
    ['tea', 'чай'],
    ['clock/watch', 'часы'],
    ['what', 'что'],
    ['excursion', 'экскурсия'],
    ['building floor', 'этаж'],

    ['excuse me (inf.)', 'извини'],
    ['excuse me (form.)', 'извините'],
    ['you may not', 'нельзя'],
    ["it's okay", 'ничего'],
    ["please/you're welcome", 'пожалуйста'],
    ['tell me (inf.)', 'скажи'],
    ['tell me (form.)', 'скажите'],
    ['What is it?', 'Что это?'],
    ['Who is it?', 'Кто это?'],
  ],
},

{ 'name': "Unit 5 Vocabulary",
  'vocab': [
    ['ticket', 'билет'],
    ['in the spring', 'весной'],
    ['visa', 'виза'],
    ['exhibition', 'выставка'],
    ['eye', 'глаз'],
    ['hotel', 'гостиница'],
    ['money', 'деньги'],
    ['children', 'дети'],
    ['sofa', 'диван'],
    ['housewife', 'домохозяйка'],
    ['daughter', 'дочь'],
    ['yet', 'ещё'],
    ['male journalist', 'журналист'],
    ['female journalist', 'журналистка'],
    ['to know', 'знать'],
    ['picture/painting', 'картина'],
    ['cinema/movie theater', 'кино'],
    ['cinema theater', 'кинотеатр'],
    ['envelope', 'конверт'],
    ['cosmonaut/astronaut', 'космонавт'],
    ['coffee', 'кофе'],
    ['armchair', 'кресло'],
    ['people', 'люди'],
    ['husband', 'муж'],
    ['night', 'ночь'],
    ['lunch', 'обед'],
    ['father', 'отец'],
    ['postcard', 'открытка'],
    ['break (resting)', 'перерыв'],

    ['writer', 'писатель'],
    ['audio player', 'плеер'],
    ['avenue', 'проспект'],
    ['psychologist', 'психолог'],
    ['child', 'ребёнок'],
    ['native/own', 'родной'],
    ['Russian Federation acronym', 'РФ'],
    ['male athlete', 'спортсмен'],
    ['female athlete', 'спортсменка'],
    ['capital', 'столица'],
    ['USA acronym', 'США'],
    ['table', 'таблица'],
    ['television', 'телевизор'],
    ['comrade/friend', 'товарищ'],
    ['tramway', 'трамвай'],
    ['already', 'уже'],
    ['street', 'улица'],
    ['farmer', 'фермер'],
    ['chemist', 'химик'],
    ['person', 'человек'],
    ['male grade school student', 'школьник'],
    ['female grade school student', 'школьница'],
    ['color', 'цвет'],
    ['price', 'цена'],
    ['cent', 'цент'],
    ['city center/downtown', 'центр'],

    ['circus', 'цирк'],
    ['digit/numeral', 'цифра'],
    ['economist', 'экономист'],
    ['attorney/lawyer', 'юрист'],

    ['nice to meet you/very pleased', 'очень приятно'],
    ["let's get acquainted", 'давайте познакомимся'],
    ['everything is ok', 'нормально'],
    ['call (someone) to the phone (inf.)', 'позови'],
    ['call (someone) to the phone (form.)', 'позовите'],
    ['see you', 'пока'],
    ['hi (inf.)', 'привет'],
  ],
},

{ 'name': "Irregular Plurals",
  'vocab': [
    ['brothers', 'братья'],
    ['male friends', 'друзья'],
    ['chairs', 'стулья'],
    ['sisters', 'сёстры'],
    ['houses', 'дома'],
    ['cities', 'города'],
    ['eyes', 'глаза'],
    ['people', 'люди'],
    ['children', 'дети'],
    ['addresses', 'адреса'],
  ],
},

{ 'name': "In-class Vocabulary",
  'vocab': [
    ['door', 'дверь'],
    ['game', 'игра'],
  ],
},

// { 'name': "",
//   'vocab': [
//     ['', ''],
//   ],
// },

];
